services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventhub
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventhub"]
      interval: 3s
      timeout: 5s
      retries: 20

  backend:
    image: php:8.3-cli
    working_dir: /var/www
    volumes:
      - ./apps/backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: |
      bash -lc "
        apt-get update && apt-get install -y libpq-dev postgresql-client git unzip &&
        docker-php-ext-install pdo pdo_pgsql &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-interaction &&
        php artisan key:generate &&

        until pg_isready -h db -p 5432 -U eventhub; do echo 'waiting for db...'; sleep 2; done &&

        php artisan migrate --force &&
        php artisan db:seed --force &&

        php artisan serve --host=0.0.0.0 --port=8000
      "

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    command: bash -lc "npm install && npm run dev -- --host"

volumes:
  db_data:
