services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventhub
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: php:8.3-cli
    working_dir: /var/www
    volumes:
      - ./apps/backend:/var/www
    ports:
      - "8000:8000"
    depends_on: [db]
    command: bash -lc "
      apt-get update && apt-get install -y libpq-dev git unzip &&
      docker-php-ext-install pdo pdo_pgsql &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: bash -lc "npm install && npm run dev -- --host"

volumes:
  db_data:
